import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'], display: 'swap' })

import { Providers } from '../providers'

export const metadata: Metadata = {
	title: 'Clean Template Nextjs',
	description: 'Generated by Gabdx',
	icons: {
		icon: {
			rel: 'icon',
			sizes: '32x32',
			url: '/coffe.png'
		}
	}
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={roboto.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
